#include <gst/gst.h>
#include <gio/gio.h>

#define GST_G_IO_MODULE_DECLARE(name) \
extern void G_PASTE(g_io_, G_PASTE(name, _load)) (gpointer data)

#define GST_G_IO_MODULE_LOAD(name) \
G_PASTE(g_io_, G_PASTE(name, _load)) (NULL)

/* Declaration of static plugins */
  GST_PLUGIN_STATIC_DECLARE(coreelements);  GST_PLUGIN_STATIC_DECLARE(coretracers);  GST_PLUGIN_STATIC_DECLARE(adder);  GST_PLUGIN_STATIC_DECLARE(app);  GST_PLUGIN_STATIC_DECLARE(audioconvert);  GST_PLUGIN_STATIC_DECLARE(audiomixer);  GST_PLUGIN_STATIC_DECLARE(audiorate);  GST_PLUGIN_STATIC_DECLARE(audioresample);  GST_PLUGIN_STATIC_DECLARE(audiotestsrc);  GST_PLUGIN_STATIC_DECLARE(compositor);  GST_PLUGIN_STATIC_DECLARE(gio);  GST_PLUGIN_STATIC_DECLARE(overlaycomposition);  GST_PLUGIN_STATIC_DECLARE(pango);  GST_PLUGIN_STATIC_DECLARE(pbtypes);  GST_PLUGIN_STATIC_DECLARE(rawparse);  GST_PLUGIN_STATIC_DECLARE(typefindfunctions);  GST_PLUGIN_STATIC_DECLARE(videoconvertscale);  GST_PLUGIN_STATIC_DECLARE(videorate);  GST_PLUGIN_STATIC_DECLARE(videotestsrc);  GST_PLUGIN_STATIC_DECLARE(volume);  GST_PLUGIN_STATIC_DECLARE(autodetect);  GST_PLUGIN_STATIC_DECLARE(videofilter);  GST_PLUGIN_STATIC_DECLARE(insertbin);  GST_PLUGIN_STATIC_DECLARE(mse);  GST_PLUGIN_STATIC_DECLARE(switchbin);  GST_PLUGIN_STATIC_DECLARE(fallbackswitch);  GST_PLUGIN_STATIC_DECLARE(gopbuffer);  GST_PLUGIN_STATIC_DECLARE(livesync);  GST_PLUGIN_STATIC_DECLARE(originalbuffer);  GST_PLUGIN_STATIC_DECLARE(rsinter);  GST_PLUGIN_STATIC_DECLARE(rstracers);  GST_PLUGIN_STATIC_DECLARE(streamgrouper);  GST_PLUGIN_STATIC_DECLARE(threadshare);  GST_PLUGIN_STATIC_DECLARE(togglerecord);  GST_PLUGIN_STATIC_DECLARE(opengl);  GST_PLUGIN_STATIC_DECLARE(ipcpipeline);  GST_PLUGIN_STATIC_DECLARE(vulkan);  GST_PLUGIN_STATIC_DECLARE(tinyalsa);  GST_PLUGIN_STATIC_DECLARE(opensles);  GST_PLUGIN_STATIC_DECLARE(alpha);  GST_PLUGIN_STATIC_DECLARE(alphacolor);  GST_PLUGIN_STATIC_DECLARE(audiofx);  GST_PLUGIN_STATIC_DECLARE(cairo);  GST_PLUGIN_STATIC_DECLARE(cutter);  GST_PLUGIN_STATIC_DECLARE(debug);  GST_PLUGIN_STATIC_DECLARE(deinterlace);  GST_PLUGIN_STATIC_DECLARE(dtmf);  GST_PLUGIN_STATIC_DECLARE(effectv);  GST_PLUGIN_STATIC_DECLARE(equalizer);  GST_PLUGIN_STATIC_DECLARE(gdkpixbuf);  GST_PLUGIN_STATIC_DECLARE(imagefreeze);  GST_PLUGIN_STATIC_DECLARE(interleave);  GST_PLUGIN_STATIC_DECLARE(level);  GST_PLUGIN_STATIC_DECLARE(multifile);  GST_PLUGIN_STATIC_DECLARE(replaygain);  GST_PLUGIN_STATIC_DECLARE(shapewipe);  GST_PLUGIN_STATIC_DECLARE(smpte);  GST_PLUGIN_STATIC_DECLARE(spectrum);  GST_PLUGIN_STATIC_DECLARE(videobox);  GST_PLUGIN_STATIC_DECLARE(videocrop);  GST_PLUGIN_STATIC_DECLARE(videomixer);  GST_PLUGIN_STATIC_DECLARE(accurip);  GST_PLUGIN_STATIC_DECLARE(aes);  GST_PLUGIN_STATIC_DECLARE(aiff);  GST_PLUGIN_STATIC_DECLARE(audiobuffersplit);  GST_PLUGIN_STATIC_DECLARE(audiofxbad);  GST_PLUGIN_STATIC_DECLARE(audiolatency);  GST_PLUGIN_STATIC_DECLARE(audiomixmatrix);  GST_PLUGIN_STATIC_DECLARE(autoconvert);  GST_PLUGIN_STATIC_DECLARE(bayer);  GST_PLUGIN_STATIC_DECLARE(coloreffects);  GST_PLUGIN_STATIC_DECLARE(closedcaption);  GST_PLUGIN_STATIC_DECLARE(debugutilsbad);  GST_PLUGIN_STATIC_DECLARE(fieldanalysis);  GST_PLUGIN_STATIC_DECLARE(freeverb);  GST_PLUGIN_STATIC_DECLARE(gaudieffects);  GST_PLUGIN_STATIC_DECLARE(geometrictransform);  GST_PLUGIN_STATIC_DECLARE(inter);  GST_PLUGIN_STATIC_DECLARE(interlace);  GST_PLUGIN_STATIC_DECLARE(ivtc);  GST_PLUGIN_STATIC_DECLARE(legacyrawparse);  GST_PLUGIN_STATIC_DECLARE(proxy);  GST_PLUGIN_STATIC_DECLARE(removesilence);  GST_PLUGIN_STATIC_DECLARE(segmentclip);  GST_PLUGIN_STATIC_DECLARE(smooth);  GST_PLUGIN_STATIC_DECLARE(speed);  GST_PLUGIN_STATIC_DECLARE(soundtouch);  GST_PLUGIN_STATIC_DECLARE(timecode);  GST_PLUGIN_STATIC_DECLARE(videofiltersbad);  GST_PLUGIN_STATIC_DECLARE(videoframe_audiolevel);  GST_PLUGIN_STATIC_DECLARE(videosignal);  GST_PLUGIN_STATIC_DECLARE(webrtcdsp);  GST_PLUGIN_STATIC_DECLARE(ladspa);  GST_PLUGIN_STATIC_DECLARE(unixfd);  GST_PLUGIN_STATIC_DECLARE(demucs);  GST_PLUGIN_STATIC_DECLARE(rsaudiofx);  GST_PLUGIN_STATIC_DECLARE(rsvideofx);  GST_PLUGIN_STATIC_DECLARE(udp);  GST_PLUGIN_STATIC_DECLARE(rtp);  GST_PLUGIN_STATIC_DECLARE(videoparsersbad);  GST_PLUGIN_STATIC_DECLARE(androidmedia);  GST_PLUGIN_STATIC_DECLARE(opengl);  GST_PLUGIN_STATIC_DECLARE(playback);  GST_PLUGIN_STATIC_DECLARE(rtpmanager);  GST_PLUGIN_STATIC_DECLARE(libav);

/* Declaration of static gio modules */
 

/* Call this function to load GIO modules */
static void
gst_android_load_gio_modules (void)
{
  GTlsBackend *backend;
  const gchar *ca_certs;

  

  ca_certs = g_getenv ("CA_CERTIFICATES");

  backend = g_tls_backend_get_default ();
  if (backend && ca_certs) {
    GTlsDatabase *db;
    GError *error = NULL;

    db = g_tls_file_database_new (ca_certs, &error);
    if (db) {
      g_tls_backend_set_default_database (backend, db);
      g_object_unref (db);
    } else {
      g_warning ("Failed to create a database from file: %s",
          error ? error->message : "Unknown");
    }
  }
}

/* This is called by gst_init() */
void
gst_init_static_plugins (void)
{
   GST_PLUGIN_STATIC_REGISTER(coreelements);  GST_PLUGIN_STATIC_REGISTER(coretracers);  GST_PLUGIN_STATIC_REGISTER(adder);  GST_PLUGIN_STATIC_REGISTER(app);  GST_PLUGIN_STATIC_REGISTER(audioconvert);  GST_PLUGIN_STATIC_REGISTER(audiomixer);  GST_PLUGIN_STATIC_REGISTER(audiorate);  GST_PLUGIN_STATIC_REGISTER(audioresample);  GST_PLUGIN_STATIC_REGISTER(audiotestsrc);  GST_PLUGIN_STATIC_REGISTER(compositor);  GST_PLUGIN_STATIC_REGISTER(gio);  GST_PLUGIN_STATIC_REGISTER(overlaycomposition);  GST_PLUGIN_STATIC_REGISTER(pango);  GST_PLUGIN_STATIC_REGISTER(pbtypes);  GST_PLUGIN_STATIC_REGISTER(rawparse);  GST_PLUGIN_STATIC_REGISTER(typefindfunctions);  GST_PLUGIN_STATIC_REGISTER(videoconvertscale);  GST_PLUGIN_STATIC_REGISTER(videorate);  GST_PLUGIN_STATIC_REGISTER(videotestsrc);  GST_PLUGIN_STATIC_REGISTER(volume);  GST_PLUGIN_STATIC_REGISTER(autodetect);  GST_PLUGIN_STATIC_REGISTER(videofilter);  GST_PLUGIN_STATIC_REGISTER(insertbin);  GST_PLUGIN_STATIC_REGISTER(mse);  GST_PLUGIN_STATIC_REGISTER(switchbin);  GST_PLUGIN_STATIC_REGISTER(fallbackswitch);  GST_PLUGIN_STATIC_REGISTER(gopbuffer);  GST_PLUGIN_STATIC_REGISTER(livesync);  GST_PLUGIN_STATIC_REGISTER(originalbuffer);  GST_PLUGIN_STATIC_REGISTER(rsinter);  GST_PLUGIN_STATIC_REGISTER(rstracers);  GST_PLUGIN_STATIC_REGISTER(streamgrouper);  GST_PLUGIN_STATIC_REGISTER(threadshare);  GST_PLUGIN_STATIC_REGISTER(togglerecord);  GST_PLUGIN_STATIC_REGISTER(opengl);  GST_PLUGIN_STATIC_REGISTER(ipcpipeline);  GST_PLUGIN_STATIC_REGISTER(vulkan);  GST_PLUGIN_STATIC_REGISTER(tinyalsa);  GST_PLUGIN_STATIC_REGISTER(opensles);  GST_PLUGIN_STATIC_REGISTER(alpha);  GST_PLUGIN_STATIC_REGISTER(alphacolor);  GST_PLUGIN_STATIC_REGISTER(audiofx);  GST_PLUGIN_STATIC_REGISTER(cairo);  GST_PLUGIN_STATIC_REGISTER(cutter);  GST_PLUGIN_STATIC_REGISTER(debug);  GST_PLUGIN_STATIC_REGISTER(deinterlace);  GST_PLUGIN_STATIC_REGISTER(dtmf);  GST_PLUGIN_STATIC_REGISTER(effectv);  GST_PLUGIN_STATIC_REGISTER(equalizer);  GST_PLUGIN_STATIC_REGISTER(gdkpixbuf);  GST_PLUGIN_STATIC_REGISTER(imagefreeze);  GST_PLUGIN_STATIC_REGISTER(interleave);  GST_PLUGIN_STATIC_REGISTER(level);  GST_PLUGIN_STATIC_REGISTER(multifile);  GST_PLUGIN_STATIC_REGISTER(replaygain);  GST_PLUGIN_STATIC_REGISTER(shapewipe);  GST_PLUGIN_STATIC_REGISTER(smpte);  GST_PLUGIN_STATIC_REGISTER(spectrum);  GST_PLUGIN_STATIC_REGISTER(videobox);  GST_PLUGIN_STATIC_REGISTER(videocrop);  GST_PLUGIN_STATIC_REGISTER(videomixer);  GST_PLUGIN_STATIC_REGISTER(accurip);  GST_PLUGIN_STATIC_REGISTER(aes);  GST_PLUGIN_STATIC_REGISTER(aiff);  GST_PLUGIN_STATIC_REGISTER(audiobuffersplit);  GST_PLUGIN_STATIC_REGISTER(audiofxbad);  GST_PLUGIN_STATIC_REGISTER(audiolatency);  GST_PLUGIN_STATIC_REGISTER(audiomixmatrix);  GST_PLUGIN_STATIC_REGISTER(autoconvert);  GST_PLUGIN_STATIC_REGISTER(bayer);  GST_PLUGIN_STATIC_REGISTER(coloreffects);  GST_PLUGIN_STATIC_REGISTER(closedcaption);  GST_PLUGIN_STATIC_REGISTER(debugutilsbad);  GST_PLUGIN_STATIC_REGISTER(fieldanalysis);  GST_PLUGIN_STATIC_REGISTER(freeverb);  GST_PLUGIN_STATIC_REGISTER(gaudieffects);  GST_PLUGIN_STATIC_REGISTER(geometrictransform);  GST_PLUGIN_STATIC_REGISTER(inter);  GST_PLUGIN_STATIC_REGISTER(interlace);  GST_PLUGIN_STATIC_REGISTER(ivtc);  GST_PLUGIN_STATIC_REGISTER(legacyrawparse);  GST_PLUGIN_STATIC_REGISTER(proxy);  GST_PLUGIN_STATIC_REGISTER(removesilence);  GST_PLUGIN_STATIC_REGISTER(segmentclip);  GST_PLUGIN_STATIC_REGISTER(smooth);  GST_PLUGIN_STATIC_REGISTER(speed);  GST_PLUGIN_STATIC_REGISTER(soundtouch);  GST_PLUGIN_STATIC_REGISTER(timecode);  GST_PLUGIN_STATIC_REGISTER(videofiltersbad);  GST_PLUGIN_STATIC_REGISTER(videoframe_audiolevel);  GST_PLUGIN_STATIC_REGISTER(videosignal);  GST_PLUGIN_STATIC_REGISTER(webrtcdsp);  GST_PLUGIN_STATIC_REGISTER(ladspa);  GST_PLUGIN_STATIC_REGISTER(unixfd);  GST_PLUGIN_STATIC_REGISTER(demucs);  GST_PLUGIN_STATIC_REGISTER(rsaudiofx);  GST_PLUGIN_STATIC_REGISTER(rsvideofx);  GST_PLUGIN_STATIC_REGISTER(udp);  GST_PLUGIN_STATIC_REGISTER(rtp);  GST_PLUGIN_STATIC_REGISTER(videoparsersbad);  GST_PLUGIN_STATIC_REGISTER(androidmedia);  GST_PLUGIN_STATIC_REGISTER(opengl);  GST_PLUGIN_STATIC_REGISTER(playback);  GST_PLUGIN_STATIC_REGISTER(rtpmanager);  GST_PLUGIN_STATIC_REGISTER(libav);
  gst_android_load_gio_modules ();
}
